Add PUT API client changes
kmdlogic/kmd-logic-file-security-client pull request #15
Opened 2021-05-18 03:59 UTC by avinashbr123

Updated swagger with the PUT API for SignConfiguration
FileSecurityClient is updated with UpdateSignConfiguration method
Updated, README.md & CHANGES.md

2021-05-18 05:41 UTC, smahapatra86 requested changes

2021-05-18 05:41 UTC, smahapatra86 commented on src/Kmd.Logic.FileSecurity.Client/FileSecurityClient.cs
> +        /// <param name="updateSignConfigurationPdfRequestDetails">Signconfiguration create request details.</param>
param description to be updated

2021-05-18 09:07 UTC, smahapatra86 approved these changes

2021-05-18 09:52 UTC, smahapatra86 approved these changes

2021-05-19 07:57 UTC, thecorrado approved these changes

2021-05-19 09:45 UTC, merged